# Generated by Django 3.0.8 on 2020-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenge', '0003_auto_20200714_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Validated'), (2, 'Validated'), (3, 'Solved')], default=1),
        ),
    ]
